# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webspot

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0a92112a73bd43fd8211fb6758fce633 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_53b08934b7d64f01a164af74207d16ba }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0a92112a73bd43fd8211fb6758fce633 }}/crawlabteam/webspot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webspot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2ceefe7dc8b8445daecd293bc1b33b30 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0a92112a73bd43fd8211fb6758fce633 }}/crawlabteam/webspot:${{ github.sha }}'