# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webspot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c3d111cc6cd542aaae437d0c87f153cf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_87fa4c8084794816aa1f6f2b02b74b15 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c3d111cc6cd542aaae437d0c87f153cf }}/crawlabteam/webspot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webspot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5d0045622fd14e3891b8d58adf0365ef }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c3d111cc6cd542aaae437d0c87f153cf }}/crawlabteam/webspot:${{ github.sha }}'