# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webspot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_88a80823956545edb33f54fe94c63b4b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cb5d26d12f1c4c08a28e02d3ecfccb28 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_88a80823956545edb33f54fe94c63b4b }}/crawlabteam/webspot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webspot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_08863d68628b48428d501714f29bf340 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_88a80823956545edb33f54fe94c63b4b }}/crawlabteam/webspot:${{ github.sha }}'